version: "3.9"
services:
  elasticsearch:
    platform: linux/amd64
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - target: 9200
        published: 9200
    networks:
      - localnetwork

  kibana:
    platform: linux/amd64
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - localnetwork      
networks:
  localnetwork:
    name: localnetwork
    driver: bridge




